tamnaye/frontend

src/component/header/Header.js

링크 보시고 하기 편하시게 수정하였습니다.
현정님과 맞춘 예약실 도메인 형태는 수정하지 않은 상태입니다.

docs : login 링크 및 예약하기 마이페이지 링크 1차 변경

---

src/component/mypage/MyBookTable.js

test test test

---

src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMap.module.css
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.module.css
src/component/main/secondFloorComponents/SecondFloorNaRoom.js
src/component/main/secondFloorComponents/SecondFloorNaRoom.module.css
src/component/main/thirdFloorComponents/ThirdFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMap.module.css
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.js
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.module.css
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.module.css

메인 버튼, 맵에 링크를 붙이고, 파람값을 룸넘버로 변경하였습니다.

feat : 메인 버튼, 맵 링크 추가 및 디자인 변경 

---

src/component/main/MainTemplate.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/reservation/ReservationState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js

민아님 메인 데이터 받아 2층 3층 구별하여 데이터를 보여주는 작업 진행

docs : 메인 api 데이터 메인페이지에 받아오기

---

src/App.js
src/component/bookpage/Navs.js
src/component/bookpage/RoomInfo.js
src/component/header/Header.js

docs : 예약페이지 파람스 url 수정

---

src/component/bookpage/BookPage.js
src/component/bookpage/RoomInfo.js
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/bookpage/navs/NavsFloor3.js
src/component/main/MainTemplate.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorNaRoom.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/reservation/ReservationState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js

변경사항 : 각 페이지 데이터 연동 및 페이지 이동 구현 완료

---

src/App.js
src/component/bookpage/BookPage.js
src/component/bookpage/RoomInfo.js
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/bookpage/navs/NavsFloor3.js
src/component/main/MainTemplate.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorNaRoom.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/mypage/MyBookTable.js
src/component/mypage/MyPage.js
src/component/reservation/ReservationState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js
src/db/userBookingData.json

mypage 더미 데이터 생성

---

src/component/bookpage/BookPage.js
src/component/bookpage/RoomInfo.js
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/bookpage/navs/NavsFloor3.js
src/component/main/MainTemplate.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorNaRoom.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js

docs : 0829 API 데이터로 수정

---

package-lock.json
package.json
public/index.html
src/component/reservation/Poplay.js
src/component/reservation/Poplay.module.css
src/component/reservation/PoplayNabox.js
src/component/reservation/PoplayNabox.module.css
src/component/reservation/ReservationState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.module.css
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorReservationState.js

feat :  예약 현황 기능 구현

---

src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.module.css
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.module.css

design : 예약 현황 페이지 블록 형식 디자인 완료

design : 예약 현황 페이지 블록 형식 디자인 완료

---

src/hooks/UseUrl.js

feat : urlHook 추가

---

src/component/bookpage/UserInfoTimeData.js
src/component/mypage/MyBookTable.js
src/component/mypage/MyBookTable.module.css
src/component/mypage/MyPage.js
src/component/mypage/MyPage.module.css

마이페이지 반응형 웹 구현

---

src/component/bookpage/RoomInfo.js
src/hooks/useRoomImg.js

roomImg 훅만들어서 사용함

---

src/component/login/Login.js
src/component/login/Login.module.css
src/component/mypage/MyBookTable.js
src/component/mypage/MyBookTable.module.css
src/component/mypage/MyBookTableEmpty.module.css
src/component/mypage/MyPage.js
src/component/mypage/MyPage.module.css

마이페이지 매니저 공식일정 및 지나간 예약시간일 경우 css적용

마이페이지 매니저 공식일, 지나간 시간일 경우 css적용

---

src/App.js
src/component/Feedback.js
src/component/bookpage/BookPage.js
src/component/bookpage/BookPage.module.css
src/component/bookpage/BookingData.js
src/component/bookpage/BookingData.module.css
src/component/bookpage/RoomInfo.js
src/component/bookpage/RoomInfo.module.css
src/component/bookpage/navs/Navs.module.css
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/header/Header.js
src/component/login/Login.js
src/component/mypage/MyBookTable.js
src/hooks/useUrl.js

예약페이지 팀원버튼 css & 피드백페이지(임시) 제작

예약페이지 팀원버튼 css & 피드백페이지(임시) 제작

---

src/component/bookpage/BookPage.module.css
src/component/bookpage/navs/Navs.module.css
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/bookpage/navs/NavsFloor3.js
src/hooks/useUrl.js

4층 회의실 추가하기

---

src/component/main/fourthFloorComponents/FourthFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js

design : 메인 마감 글귀 수정

---

src/component/bookpage/BookingData.js
src/hooks/useUrl.js

주말 예약 버튼 비활성화

---

src/component/reservation/FourthFloorStateComponents/FourthFloorMeetingRoomState.js
src/component/reservation/FourthFloorStateComponents/FourthFloorMeetingRoomState.module.css
src/hooks/useUrl.js

design : 4층 예약 현황 수정

---

src/component/mypage/MyBookTable.js

시간이 지난경우 예약취소 버튼을 사용완료로 변경

---

src/component/mypage/MyBookTable.js
src/hooks/useUrl.js

마이페이지 예약취소버튼 조건 수정

---

src/component/main/thirdFloorComponents/ThirdFloorMap.module.css
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.module.css

design : 글자 위치 수정

---

src/component/bookpage/BookingData.module.css
src/hooks/useRoomImg.js

roomImg 데이터 변경

---

src/component/bookpage/BookingData.js
src/component/bookpage/BookingData.module.css

팀원선택 버튼 높이 조정

---

src/component/main/fourthFloorComponents/FourthFloorMap.js
src/component/main/fourthFloorComponents/FourthFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorNaRoom.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js
src/component/main/thirdFloorComponents/ThirdFloorMeetingRoom.js
src/component/main/thirdFloorComponents/ThirdFloorNaRoom.js
src/component/reservation/FourthFloorStateComponents/FourthFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorMeetingRoomState.js
src/component/reservation/SecondFloorStateComponents/SecondFloorNaRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js
src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorNaRoomState.js

test 이후 디테일 수정

---

src/component/bookpage/BookingData.js
src/component/bookpage/BookingData.module.css

무결님 BookData.js 파일 수정이라 충돌날거 같아서 요청만 할게요!

팀원 데이터 불러오기 모달창 구현(outside클릭 시 모달창 사라짐)

---

src/component/reservation/ThirdFloorStateComponents/ThirdFloorMeetingRoomState.js

fix : 예약 현황 페이지 스튜디오 poplay 수정

fix : 예약 현황 페이지 스튜디오 poplay 수정

---

src/App.js
src/component/header/Header.js
src/component/login/Login.js
src/component/mypage/MyPage.js

feedback 컴포넌트 주석처리

---

src/component/adminPages/classesFloor/ClassesFloor.js

변경사항 : UploadFile & ClassFloor Js로 새로고침

UploadFile & ClassFloor Js로 새로고침

---

src/component/main/MainTemplate.js
src/component/main/fourthFloorComponents/FourthFloor.js
src/component/main/fourthFloorComponents/FourthFloorMap.js
src/component/main/fourthFloorComponents/FourthFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloor.js
src/component/main/thirdFloorComponents/ThirdFloor.js
src/component/main/thirdFloorComponents/ThirdFloorMap.js

refactor : 메인 전체 데이터 구조 MainTemplate에서 props로 받아오도록변경

refactor : 메인 전체 데이터 구조 MainTemplate에서 props로 받아오도록변경

---

src/component/adminPages/fileUpload/FileUpload.js
src/component/bookpage/BookPage.js
src/component/bookpage/BookingData.js
src/component/bookpage/RoomInfo.js
src/component/bookpage/navs/NavsAdmin.js
src/component/bookpage/navs/NavsFloor2.js
src/component/bookpage/navs/NavsFloor3.js

변경사항 : bookpage에서 서번 한번에 받아서 navs컴포넌트에 props 전달

bookpage에서 서번 한번에 받아서 navs컴포넌트에 props 전달

---

src/component/reservation/ReservationState.js

fix : reservation state post url 수정

fix : reservation state post url 수정

---

src/component/adminPages/AdminMain.js
src/component/adminPages/classesFloor/ClassesFloor.js
src/component/adminPages/fileUpload/FileUpload.js
src/component/mypage/MyBookTable.js
src/component/mypage/MyPage.js

review2 push ALLFloor  

---

src/component/adminPages/classesFloor/ClassesFloor.js

변경사항 : ClassesFloor newArr prc

ClassesFloor newArr prc

---

src/component/Feedback.js

feedback scroll 적용

---

src/component/adminPages/individual/IndividualMain.js
src/component/main/MainTemplate.js
src/component/main/secondFloorComponents/SecondFloor.js
src/component/main/secondFloorComponents/SecondFloorMap.js
src/component/main/secondFloorComponents/SecondFloorMap.module.css
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.js
src/component/main/secondFloorComponents/SecondFloorMeetingRoom.module.css
src/component/main/thirdFloorComponents/ThirdFloorMap.module.css
src/component/reservation/AllFloorReservationState.module.css
src/component/reservation/SecondFloorStateComponents/SecondFloorReservationState.module.css
src/component/reservation/ThirdFloorStateComponents/ThirdFloorReservationState.module.css
src/hooks/useUrl.js

fix : 신양, map 글씨 깨지는 것 수정

---

src/component/bookpage/BookingButton.js
src/component/bookpage/Test.js
src/hooks/useTimeAbled.js

BookingButton_useTimeAbled Hook 생성
